# -*- coding: utf-8 -*-
"""Predictive Sales Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XXnOgaJINA-2p0E4jUHvEB2JOvHfCb8
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

months1 = np.array([1,2,3,4,5,6]).reshape(-1,1)
sales1 = np.array([100,120,135,150,170,190])

months2 = np.array([1,2,3,4,5,6]).reshape(-1,1)
sales2 = np.array([200,230,280,350,420,510])

model1 = LinearRegression()
model1.fit(months1, sales1)

model2 = LinearRegression()
model2.fit(months2, sales2)

future_months = np.array([7,8,9,10,11,12]).reshape(-1,1)

pred1 = model1.predict(future_months)
pred2 = model2.predict(future_months)

plt.figure(figsize=(8,5))

plt.plot(months1, sales1, marker='o', label="Actual Sales")
plt.plot(future_months, pred1, marker='o', linestyle='dashed', label="Forecast")

plt.title("Forecast - Normal Business Growth")
plt.xlabel("Months")
plt.ylabel("Sales")
plt.legend()
plt.grid(True)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(months2, sales2, marker='o', label="Actual Sales")
plt.plot(future_months, pred2, marker='o', linestyle='dashed', color='red', label="Forecast")

plt.title("Forecast - High Growth Business")
plt.xlabel("Months")
plt.ylabel("Sales")
plt.legend()
plt.grid(True)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(future_months, pred1, label="Normal Growth Forecast")
plt.plot(future_months, pred2, label="High Growth Forecast")

plt.title("Sales Forecast Comparison")
plt.xlabel("Months")
plt.ylabel("Predicted Sales")
plt.legend()
plt.grid(True)

plt.show()

print("Normal Growth Prediction:")
for m, s in zip(future_months, pred1):
    print(f"Month {m[0]} → {s:.2f}")

print("\nHigh Growth Prediction:")
for m, s in zip(future_months, pred2):
    print(f"Month {m[0]} → {s:.2f}")